### ISSUE TITLE
reaselse 版本里缺少文件

### ISSUE THREAD

**Issue by fansmc** [GcsSloop/Rocker#4]
没有 com.gcssloop.view.utils.DensityUtils;
 com.gcssloop.view.utils.MathUtils; 这两个文件

**Comment by GcsSloop** [comment]
这两个文件在ViewSupport中，如果使用gradle添加依赖的话，这两个文件会自动添加上去的，如果手动导入需要同时导入ViewSupport仓库。

**Comment by fansmc** [comment]
采用gradle 同步后，自动导入了
