### ISSUE TITLE
如何获取摇杆实时的位置

### ISSUE THREAD

**Issue by Mokyyds** [GcsSloop/Rocker#5]
如何获取摇杆实时的位置呢？就是摇杆的具体坐标，我想根据用户拉的长度进行相应的逻辑处理。麻烦您解答一下，谢谢了。

**Comment by GcsSloop** [comment]
由于设计的时候速度是用另外一个控件控制的，所以这个里面只有控制方向的逻辑。

如果想要通过拖动的长度(距离中心的距离)来控制速度的话也很简单，计算一下用户触摸位置距离中心点的距离就行了。

源码比较简单，你自己修改一下就行，如果需要的话，我可以在这周日制作一个新版本，添加上这一功能。

**Comment by zzxxtt** [comment]
十分感谢，能否增加此功能并添加到JitPack仓库，这样方便调用。

**Comment by GcsSloop** [comment]
已经在监听器中添加了一个获取距离的字段。
